---
title: "Untitled"
output: html_document
date: "2023-06-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


$$

\newcommand{\indep}{\perp\!\!\!\perp}

A \indep B

$$


$Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$

  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~temp,~variedades~cafe$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~variedades~cafe,~volat~mun$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~uso~suelo~apisaje,~variedades~cafe$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~precio~local~20,~precip,~prod~org,~sombra~arbol,~sup~procafe,~temp,~variedades~cafe$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe,~volat~mun$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~sup~difer,~uso~suelo~apisaje$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~sup~difer,~temp$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~sup~difer,~volat~mun$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~sup~difer,~sup~procafe$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~sup~difer,~sup~procafe,~uso~suelo~apisaje$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~precio~local~20,~precip,~sup~difer,~sup~procafe,~temp$
  $Prod~tipo~ \indep ~rendimiento~~| ~Diversfc~agricola,~precio~local~20,~sup~difer,~sup~procafe,~volat~mun$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~temp,~variedades~cafe$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~variedades~cafe,~volat~mun$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~sup~difer,~uso~suelo~apisaje$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~sup~difer,~temp$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~sup~difer,~volat~mun$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~sup~difer,~sup~procafe$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~uso~suelo~apisaje,~variedades~cafe$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~precio~local~20,~precip,~prod~org,~sombra~arbol,~sup~procafe,~temp,~variedades~cafe$
  $lengua~ \indep ~rendimiento~~| ~Diversfc~agricola,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe,~volat~mun$
  $lengua~ \indep ~rendimiento~~| ~prod~org,~sup~difer,~sup~procafe$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~temp,~variedades~cafe$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~variedades~cafe,~volat~mun$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~uso~suelo~apisaje,~variedades~cafe$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~precio~local~20,~precip,~prod~org,~sombra~arbol,~sup~procafe,~temp,~variedades~cafe$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe,~volat~mun$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~sup~difer,~uso~suelo~apisaje$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~sup~difer,~temp$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~sup~difer,~volat~mun$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~sup~difer,~sup~procafe$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~sup~difer,~sup~procafe,~uso~suelo~apisaje$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~precio~local~20,~precip,~sup~difer,~sup~procafe,~temp$
  $precio~inter~ \indep ~rendimiento~~| ~Diversfc~agricola,~precio~local~20,~sup~difer,~sup~procafe,~volat~mun$
  $precip~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
  $precip~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe$
  $precip~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $precip~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~sup~difer,~sup~procafe$
  $precip~ \indep ~rendimiento~~| ~Suelo,~benef~hidro,~dens~cafe,~ingreso,~volat~mun$
  $precip~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $precip~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~uso~suelo~apisaje,~variedades~cafe$
  $precip~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~sup~difer,~uso~suelo~apisaje$
  $precip~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~sup~difer,~sup~procafe,~uso~suelo~apisaje$
  $precip~ \indep ~rendimiento~~| ~Suelo,~benef~hidro,~dens~cafe,~uso~suelo~apisaje,~volat~mun$
  $prod~org~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
  $prod~org~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $prod~org~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~temp,~variedades~cafe$
  $prod~org~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~variedades~cafe,~volat~mun$
  $prod~org~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $prod~org~ \indep ~rendimiento~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~sup~difer,~uso~suelo~apisaje$
  $prod~org~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~sup~difer,~temp$
  $prod~org~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~sup~difer,~volat~mun$
  $prod~org~ \indep ~rendimiento~~| ~Diversfc~agricola,~capacitacion,~sup~difer,~sup~procafe$
  $rendimiento~ \indep ~sup~difer~~| ~Diversfc~agricola,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe,~volat~mun$
  $rendimiento~ \indep ~sup~difer~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~variedades~cafe,~volat~mun$
  $rendimiento~ \indep ~sup~difer~~| ~Diversfc~agricola,~precio~local~20,~precip,~prod~org,~sombra~arbol,~sup~procafe,~temp,~variedades~cafe$
  $rendimiento~ \indep ~sup~difer~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~temp,~variedades~cafe$
  $rendimiento~ \indep ~sup~difer~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~uso~suelo~apisaje,~variedades~cafe$
  $rendimiento~ \indep ~sup~difer~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe$
  $rendimiento~ \indep ~sup~difer~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $rendimiento~ \indep ~sup~difer~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
  $rendimiento~ \indep ~sup~procafe~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~sup~difer,~volat~mun$
  $rendimiento~ \indep ~sup~procafe~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~variedades~cafe,~volat~mun$
  $rendimiento~ \indep ~sup~procafe~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~sup~difer,~temp$
  $rendimiento~ \indep ~sup~procafe~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~temp,~variedades~cafe$
  $rendimiento~ \indep ~sup~procafe~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~sup~difer,~uso~suelo~apisaje$
  $rendimiento~ \indep ~sup~procafe~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $rendimiento~ \indep ~sup~procafe~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $rendimiento~ \indep ~sup~procafe~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
  $rendimiento~ \indep ~temp~~| ~Suelo,~benef~hidro,~dens~cafe,~uso~suelo~apisaje,~volat~mun$
  $rendimiento~ \indep ~temp~~| ~Suelo,~benef~hidro,~dens~cafe,~ingreso,~volat~mun$
  $rendimiento~ \indep ~temp~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~sup~difer,~sup~procafe,~uso~suelo~apisaje$
  $rendimiento~ \indep ~temp~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~sup~difer,~sup~procafe$
  $rendimiento~ \indep ~temp~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~sup~difer,~uso~suelo~apisaje$
  $rendimiento~ \indep ~temp~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $rendimiento~ \indep ~temp~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~uso~suelo~apisaje,~variedades~cafe$
  $rendimiento~ \indep ~temp~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe$
  $rendimiento~ \indep ~temp~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $rendimiento~ \indep ~temp~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
  $rendimiento~ \indep ~tipo~sup~soc~~| ~prod~org$
  $rendimiento~ \indep ~tipo~sup~soc~~| ~Diversfc~agricola,~capacitacion,~sup~difer,~sup~procafe$
  $rendimiento~ \indep ~tipo~sup~soc~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~sup~difer,~volat~mun$
  $rendimiento~ \indep ~tipo~sup~soc~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~sombra~arbol,~variedades~cafe,~volat~mun$
  $rendimiento~ \indep ~tipo~sup~soc~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~sup~difer,~temp$
  $rendimiento~ \indep ~tipo~sup~soc~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~temp,~variedades~cafe$
  $rendimiento~ \indep ~tipo~sup~soc~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~sup~difer,~uso~suelo~apisaje$
  $rendimiento~ \indep ~tipo~sup~soc~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $rendimiento~ \indep ~tipo~sup~soc~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $rendimiento~ \indep ~tipo~sup~soc~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
  $rendimiento~ \indep ~uso~agroquim~~| ~Suelo,~benef~hidro,~dens~cafe,~precip,~temp,~uso~suelo~apisaje$
  $rendimiento~ \indep ~uso~agroquim~~| ~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precip,~temp$
  $rendimiento~ \indep ~uso~agroquim~~| ~Suelo,~benef~hidro,~dens~cafe,~uso~suelo~apisaje,~volat~mun$
  $rendimiento~ \indep ~uso~agroquim~~| ~Suelo,~benef~hidro,~dens~cafe,~ingreso,~volat~mun$
  $rendimiento~ \indep ~uso~agroquim~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~sup~difer,~sup~procafe,~uso~suelo~apisaje$
  $rendimiento~ \indep ~uso~agroquim~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~sup~difer,~sup~procafe$
  $rendimiento~ \indep ~uso~agroquim~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~sup~difer,~uso~suelo~apisaje$
  $rendimiento~ \indep ~uso~agroquim~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $rendimiento~ \indep ~uso~agroquim~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~uso~suelo~apisaje,~variedades~cafe$
  $rendimiento~ \indep ~uso~agroquim~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe$
  $rendimiento~ \indep ~uso~agroquim~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $rendimiento~ \indep ~uso~agroquim~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
  $rendimiento~ \indep ~uso~suelo~apisaje~~| ~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precip,~temp$
  $rendimiento~ \indep ~uso~suelo~apisaje~~| ~Suelo,~benef~hidro,~dens~cafe,~ingreso,~volat~mun$
  $rendimiento~ \indep ~uso~suelo~apisaje~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~sup~difer,~sup~procafe$
  $rendimiento~ \indep ~uso~suelo~apisaje~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $rendimiento~ \indep ~uso~suelo~apisaje~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe$
  $rendimiento~ \indep ~uso~suelo~apisaje~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~precio~local~20,~precip,~sup~difer,~sup~procafe,~temp$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~sup~difer,~temp$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~precio~local~20,~precip,~prod~org,~sombra~arbol,~sup~procafe,~temp,~variedades~cafe$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~capacitacion,~precio~local~20,~precip,~sombra~arbol,~temp,~variedades~cafe$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~sup~difer,~sup~procafe,~uso~suelo~apisaje$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~sup~difer,~sup~procafe$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~sup~difer,~uso~suelo~apisaje$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~sup~difer$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~uso~suelo~apisaje,~variedades~cafe$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~dens~cafe,~ingreso,~precio~local~20,~prod~org,~sombra~arbol,~sup~procafe,~variedades~cafe$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~precio~local~20,~sombra~arbol,~uso~suelo~apisaje,~variedades~cafe$
  $rendimiento~ \indep ~volat~mun~~| ~Diversfc~agricola,~Suelo,~benef~hidro,~capacitacion,~dens~cafe,~ingreso,~precio~local~20,~sombra~arbol,~variedades~cafe$
